[tool.poetry]
name = "activewindow"
version = "0.1.0"
description = ""
authors = ["Sander van Dragt <sander@vandragt.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
PyGObject = "^3.46.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
